import { Level, Status } from '@prisma/client';
export const NAMES = [
  'John',
  'Jack',
  'Mary',
  'Jane',
  'Mike',
  'Mark',
  'Matthew',
  'Michael',
  'Mohamed',
  'Muhammad',
  'Nicolas',
  'Noah',
  'Oliver',
  'Omar',
  'Oscar',
  'Patrick',
  'Paul',
  'Peter',
  'Philip',
  'Richard',
  'Robert',
  'Ryan',
  'Samuel',
  'Sebastian',
  'Simon',
  'Stephen',
  'Thomas',
  'Timothy',
  'Tobias',
  'Tom',
  'Victor',
  'William',
  'Xavier',
  'Yann',
  'Zachary',
  'Zach',
  'Zoe',
  'Zara',
];

export const SURNAMES = [
  'Smith',
  'Johnson',
  'Williams',
  'Jones',
  'Brown',
  'Davis',
  'Miller',
  'Wilson',
  'Moore',
  'Taylor',
  'Anderson',
  'Thomas',
  'Jackson',
  'White',
  'Harris',
  'Martin',
  'Thompson',
  'Garcia',
  'Martinez',
  'Robinson',
  'Clark',
  'Rodriguez',
  'Lewis',
  'Lee',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'Hernandez',
  'King',
  'Wright',
  'Lopez',
  'Hill',
  'Scott',
  'Green',
  'Adams',
  'Baker',
  'Nelson',
  'Carter',
  'Mitchell',
];

export const LESSONS = [
  {
    name: 'Math',
    level: Level.BEGINNER,
    status: Status.ACTIVE,
    duration: 6,
  },
  {
    name: 'Turkish',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 5,
  },
  {
    name: 'English',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 3,
  },
  {
    name: 'Science',
    level: Level.ADVANCED,
    status: Status.ACTIVE,
    duration: 4,
  },
  {
    name: 'History',
    level: Level.ADVANCED,
    status: Status.INACTIVE,
    duration: 3,
  },
  {
    name: 'Art',
    level: Level.BEGINNER,
    status: Status.ACTIVE,
    duration: 2,
  },
  {
    name: 'Music',
    level: Level.BEGINNER,
    status: Status.INACTIVE,
    duration: 1,
  },
  {
    name: 'Spanish',
    level: Level.BEGINNER,
    status: Status.ACTIVE,
    duration: 2,
  },
  {
    name: 'French',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 7,
  },
  {
    name: 'Software Development',
    level: Level.ADVANCED,
    status: Status.ACTIVE,
    duration: 8,
  },
  {
    name: 'Web Development',
    level: Level.BEGINNER,
    status: Status.ACTIVE,
    duration: 7,
  },
  {
    name: 'Database',
    level: Level.ADVANCED,
    status: Status.INACTIVE,
    duration: 12,
  },
  {
    name: 'Photography',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 4,
  },
  {
    name: 'Biology',
    level: Level.ADVANCED,
    status: Status.ACTIVE,
    duration: 5,
  },
  {
    name: 'Psychology',
    level: Level.INTERMEDIATE,
    status: Status.INACTIVE,
    duration: 6,
  },
  {
    name: 'Physics',
    level: Level.ADVANCED,
    status: Status.ACTIVE,
    duration: 9,
  },
  {
    name: 'Chemistry',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 7,
  },
  {
    name: 'Economics',
    level: Level.ADVANCED,
    status: Status.INACTIVE,
    duration: 8,
  },
  {
    name: 'Graphic Design',
    level: Level.BEGINNER,
    status: Status.ACTIVE,
    duration: 5,
  },
  {
    name: 'Marketing',
    level: Level.INTERMEDIATE,
    status: Status.ACTIVE,
    duration: 4,
  },
];
